schema: 1
story: '1.5'
story_title: 'Swagger/OpenAPI 导出'
gate: 'CONCERNS'
status_reason: 'CI has OpenAPI export/lint/diff; runtime route /api/__openapi.json missing.'
reviewer: 'Quinn (Test Architect)'
updated: '2025-09-22T06:52:26.100892+00:00'

waiver: { active: false }

top_issues:
  - id: 'API-OPENAPI-001'
    severity: high
    finding: 'No runtime Swagger route to serve the spec.'
    suggested_action: 'Expose /api/__openapi.json from API service.'
  - id: 'BUILD-OPENAPI-001'
    severity: medium
    finding: 'Types/client generation not integrated with build/release.'
    suggested_action: 'Wire api:types/api:client into build or publishing.'

risk_summary:
  totals: { critical: 0, high: 1, medium: 1, low: 0 }
  recommendations:
    must_fix:
      - 'Add runtime route for OpenAPI.'
    monitor:
      - 'Keep Spectral warnings actionable; manage rule waivers.'
