schema: 1
story: '7.3'
story_title: '型谱规则配置'
gate: 'CONCERNS'
status_reason: 'Initial gate: 规则版本/热更新与重算一致性需验证。'
reviewer: 'Quinn (Test Architect)'
updated: '2025-09-22T06:52:26.100892+00:00'

waiver: { active: false }

top_issues:
  - id: 'RULE-DRIFT-001'
    severity: medium
    finding: '规则漂移导致结果不一致风险。'
    suggested_action: '绑定版本并在热更新后触发回放/重算测试。'

risk_summary:
  totals: { critical: 0, high: 0, medium: 1, low: 0 }
  recommendations:
    must_fix:
      - '完善 RBAC/审批与审计。'
    monitor:
      - '联动样本变更影响。'

