name: Quality Gates
on:
  pull_request:
    branches: [main, next, develop]
  push:
    branches: [main, next, develop]

concurrency:
  group: quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node & Corepack
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: corepack enable
      - run: yarn --version
      - name: Install dependencies (immutable)
        run: |
          mkdir -p reports
          START=$(date +%s)
          yarn install --immutable
          END=$(date +%s)
          DURATION=$((END-START))
          echo "yarn_install_seconds=$DURATION" | tee reports/yarn-install-metrics.txt
      - run: git diff --exit-code yarn.lock
      - name: Record Yarn cache metadata
        run: |
          mkdir -p reports
          echo "cache-hit=${{ steps.setup_node.outputs.cache-hit }}" | tee reports/yarn-cache.txt
      - name: Verify Yarn config guards
        run: |
          yarn config get nodeLinker | tee reports/nodeLinker.txt
          if ! grep -q 'node-modules' reports/nodeLinker.txt; then
            echo 'nodeLinker 未配置为 node-modules';
            exit 1;
          fi
          yarn workspaces list --json > reports/workspaces.json
          node scripts/workspace-smoke.cjs
      - run: yarn lint
      - run: yarn prettier:check
      - run: yarn type-check
      - run: yarn test:web
      - run: yarn test:api
      - name: Export OpenAPI
        run: yarn api:openapi
      - name: Spectral lint
        run: npx @stoplight/spectral-cli lint docs/openapi.json --format sarif -o reports/spectral.sarif
      - name: OpenAPI diff (vs baseline)
        run: |
          if [ -f docs/openapi.baseline.json ]; then \
            npx @redocly/openapi-cli@latest diff docs/openapi.baseline.json docs/openapi.json > reports/openapi-diff.txt || true; \
          else \
            echo 'No baseline found' > reports/openapi-diff.txt; \
          fi
      - name: Generate Types & Client
        run: |
          yarn api:types
          yarn api:client
      - name: Upload contract artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contracts
          path: |
            docs/openapi.json
            reports/spectral.sarif
            reports/openapi-diff.txt
            reports/nodeLinker.txt
            reports/workspaces.json
            reports/yarn-install-metrics.txt
            reports/yarn-cache.txt

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git -v --report-path reports/gitleaks.sarif --format sarif
      - name: OSV scan (lockfile + workspace)
        uses: google/osv-scanner-action@v1
        with:
          scan-args: >-
            --lockfile=./yarn.lock
            --recursive .
      - name: Upload security artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security
          path: reports/
